##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.8.0-B50] date: [Fri Feb 20 11:36:41 CET 2026] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = TSCube
VERSIONED_TARGET := $(TARGET)

######################################
# building variables
######################################
# debug build? 
# >>> SielTre: the viariable 'DEBUG' must be specified by make command
# e.g. make -j5 all DEBUG=1
DEBUG ?= 1

# optimization for debugging
OPT = -Og
ifeq ($(DEBUG),0)
# optimization for Release
	OPT = -O2
endif


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build
FINAL_DIR = bin

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/stm32f4xx_it.c \
Core/Src/stm32f4xx_hal_msp.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c \
Core/Src/system_stm32f4xx.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.c \
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c \
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c \
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c \
Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c \
USB_DEVICE/App/usb_device.c \
USB_DEVICE/App/usbd_desc.c \
USB_DEVICE/App/usbd_cdc_if.c \
USB_DEVICE/Target/usbd_conf.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c \
Core/Src/freertos.c \
Core/Src/stm32f4xx_hal_timebase_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
Middlewares/Third_Party/FreeRTOS/Source/list.c \
Middlewares/Third_Party/FreeRTOS/Source/queue.c \
Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
Middlewares/Third_Party/FreeRTOS/Source/timers.c \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/FreeRTOS_ARP.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/FreeRTOS_DHCP.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS_Cache.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS_Callback.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS_Networking.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS_Parser.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/FreeRTOS_ICMP.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/FreeRTOS_IP.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/FreeRTOS_IP_Timers.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/FreeRTOS_IP_Utils.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/FreeRTOS_Sockets.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/FreeRTOS_Stream_Buffer.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_IP.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Reception.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_State_Handling.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Transmission.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Utils.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_WIN.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/FreeRTOS_Tiny_TCP.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/FreeRTOS_UDP_IP.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/portable/NetworkInterface/STM32Fxx/stm32fxx_hal_eth.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/portable/NetworkInterface/STM32Fxx/NetworkInterface.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/portable/NetworkInterface/Common/phyHandling.c \
Middlewares/Third_Party/FreeRTOS-Plus-TCP/source/portable/BufferManagement/BufferAllocation_1.c \
Common/Src/mem_siel_rtos.c \
Common/Src/common_tasks.c \
Common/Src/Protocol/SielPtcl.c \
Common/Src/usbcomm.c \
Common/Src/gescom.c \
Common/Src/common_data.c \
Common/Src/lan_init.c \
Common/Src/Protocol/Codop.c \
Common/Src/lan_gescom.c \
Common/Src/common_ticker.c \
Common/Src/verifica_connessione.c \
Common/Src/AutomaPing.c \
Application/Src/GestIO.c \
Application/Src/appl_tasks.c \
Application/Src/data.c \
Application/Src/sbanc.c \
Application/Src/AppCodOp.c \
Application/Src/SpiUart_SC16IS762.c \
Application/Src/lancom_bridge.c \
Application/Src/lancom_helper.c \
Application/Src/circ_buffer.c \
Application/Src/ticker.c

# ATTENZIONE! Questo sorgente standard CMSIS-STM32 viene rimpiazzato da FreeRTOS-Plus-TCP
#Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c


# ASM sources
ASM_SOURCES =  \
startup_stm32f427xx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

DEL = rm -fR

ifeq ($(OS),Windows_NT)
	COPY = busybox cp
else
	COPY = cp
endif

#test -f /bin/sh && DEL = rm -fR
#test ! -f /bin/sh || DEL = Remove-Item -Recurse -Path
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines (aggiunto USE_HAL_USART per evitare di passare dal vecchio gescom)
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DUSE_HAL_USART \
-DSTM32F427xx \
-DSTM32F4xx=1 \
-DUSA_LOADER

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICommon/Inc \
-ICore/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include \
-IApplication/Inc \
-IUSB_DEVICE/App \
-IUSB_DEVICE/Target \
-IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc \
-IMiddlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc \
-IMiddlewares/Third_Party/FreeRTOS/Source/include \
-IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
-IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
-IMiddlewares/Third_Party/FreeRTOS-Plus-TCP/source/include \
-IMiddlewares/Third_Party/FreeRTOS-Plus-TCP/source/portable/Compiler/GCC \
-IMiddlewares/Third_Party/FreeRTOS-Plus-TCP/source/portable/NetworkInterface/include \
-IMiddlewares/Third_Party/FreeRTOS-Plus-TCP/source/portable/NetworkInterface/STM32Fxx

ifeq ($(DEBUG), 1)
C_DEFS += \
#-DNOWATCHDOG \
-DUART_DEBUG
VERSIONED_TARGET := $(VERSIONED_TARGET)-9.9.9
endif

#assigning build variables
ifeq ($(DEBUG),0)
  ifeq ($(VERSION),) 
  $(error VERSION must be filled this way 'MAJOR.minor.Build')
  endif
  APP_V1 := $(shell echo $(VERSION) | awk -F"." '{ print $$1 }')
  APP_V2 := $(shell echo $(VERSION) | awk -F"." '{ print $$2 }')
  APP_V3 := $(shell echo $(VERSION) | awk -F"." '{ print $$3 }')
  BUILD_YEAR := $(shell date '+%y' | sed 's/^0//' )
  BUILD_MONTH := $(shell date '+%m' | sed 's/^0//' )
  BUILD_DAY := $(shell date '+%d' | sed 's/^0//' )
  VERSIONED_TARGET := $(VERSIONED_TARGET)-$(VERSION)
endif

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

BLDFLAGS = 

ifeq ($(DEBUG),0)
BLDFLAGS = -DAPPL_VER_0=$(APP_V1) -DAPPL_VER_1=$(APP_V2) -DAPPL_VER_2=$(APP_V3) -DAPPL_BYEA=$(BUILD_YEAR) -DAPPL_BMON=$(BUILD_MONTH) -DAPPL_BDAY=$(BUILD_DAY) 
endif

ifeq ($(DEBUG),1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
#LDSCRIPT = STM32F427XX_FLASH.ld # TERMINAL_SERVER.ld
LDSCRIPT = TERMINAL_SERVER.ld

# libraries
LIBS = -lc -lm -lnosys
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: final_targets

final_targets: $(FINAL_DIR)/$(VERSIONED_TARGET).elf $(FINAL_DIR)/$(VERSIONED_TARGET).hex $(FINAL_DIR)/$(VERSIONED_TARGET).bin $(FINAL_DIR)/$(VERSIONED_TARGET).map

$(FINAL_DIR)/$(VERSIONED_TARGET).% : $(BUILD_DIR)/$(TARGET).% | $(FINAL_DIR)
	$(COPY) $< $@
$(BUILD_DIR)/$(TARGET).map : $(BUILD_DIR)/$(TARGET).elf

#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/data.o : Application/Src/data.c | $(BUILD_DIR)
	$(CC) -c $(CFLAGS) $(BLDFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@

$(FINAL_DIR):
	mkdir $@

#######################################
# clean up
#######################################
clean:
	$(DEL) $(BUILD_DIR)
	$(DEL) $(FINAL_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

-include Makefile.gitlab

# *** EOF ***
